# Listener TCP plano (dev only)
listener 1883 0.0.0.0
allow_anonymous true

# Persistencia de mensajes retenidos (no crítica, pero limpia los logs)
persistence true
persistence_location /mosquitto/data/

# Logging a stdout para que docker logs funcione
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
