apiVersion: 1

contactPoints:
  - orgId: 1
    name: console-default
    receivers:
      - uid: console-receiver
        type: webhook
        settings:
          url: http://localhost:9999/noop
          httpMethod: POST
        disableResolveMessage: false
